# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rebuild Docs

on: [push, pull_request]

jobs:
  resources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdoc
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc3
      - name: Run pdoc
        run: pdoc --html --output-dir doc --config show_source_code=True --force utility
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: doc/
          commit-msg: update documentation
          github-token: ${{ secrets.GITHUB_TOKEN }}
