# This action will run pdoc to build a html documentation after every push
# If something changed, the changes will be committed to the current branch
# See for more info: https://github.com/ad-m/github-push-action

name: Update Docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pdoc
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc3
          if [ -f python_requirements.txt ]; then pip install -r python_requirements.txt; fi
      - name: Run pdoc
        run: pdoc --html --output-dir doc --config show_source_code=True --force utility
      - name: Commit files
        run: |
          if [[ `git status doc/* --porcelain` ]]; then
            # Changes occurred
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add doc/*
            git commit -m "automatic rebuild of the documentation"
          else
            # No changes
            echo no changes detected
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

# BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3-)
