# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rebuild Docs

on: [push, pull_request]

jobs:
  resources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdoc
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdoc3
          if [ -f python_requirements.txt ]; then pip install -r python_requirements.txt; fi
      - name: Run pdoc
        run: pdoc --html --output-dir doc --config show_source_code=True --force utility
      - name: push changes
        run: |
          git remote set-url origin ${{ secrets.ssh }}
          if [[ `git status doc/* --porcelain` ]]; then
            # Changes
            BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3-)
            git add doc/*
            git commit -m "automatic rebuild of documentation"
            git fetch origin $BRANCH
            git push origin HEAD:$BRANCH
          else
            # No changes
            echo no changes detected
          fi


# echo GITHUB_REF: ${GITHUB_REF}
# echo GITHUB_REF branch: ${GITHUB_REF##*/}
# BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3-)
# echo branch: $BRANCH

# git config --global user.name "github-actions[bot]"
# git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
# git remote set-url origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/rol1510/utility.git"

# git checkout $BRANCH
# git add doc/*
# git commit -m "automatic rebuild of documentation"
# git push --set-upstream origin $BRANCH